# Generated by Django 5.2.1 on 2025-05-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
